name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lint Docker Compose file
      run: |
        # Проверка синтаксиса docker-compose
        docker-compose config

    - name: Build Docker Compose services
      run: |
        # Сборка всех сервисов без кэша
        docker-compose build --no-cache

    - name: Start services
      run: |
        # Запуск сервисов в фоновом режиме
        docker-compose up -d

    - name: Check service status
      run: |
        # Проверка статуса сервисов
        docker-compose ps
        docker-compose logs

    - name: Run health checks
      run: |
        # Пример базовых проверок (адаптируйте под свой проект)
        # Проверка доступности портов или эндпоинтов
        for service in $(docker-compose ps --services); do
          echo "Checking service: $service"
          # Замените на реальную проверку вашего сервиса
          docker-compose exec -T $service curl -f http://localhost:8000 || exit 1
        done

    - name: Stop and clean up
      if: always()
      run: |
        # Остановка и удаление контейнеров
        docker-compose down
        docker-compose rm -f
